#!/bin/bash

echo "Building docker image..."

docker build -t asia-southeast2-docker.pkg.dev/hidroqu/hidroqu-image/hidroqu-ml:latest .

echo "Build image completed!"

sleep 3

echo "Push image into artifact..."

docker push asia-southeast2-docker.pkg.dev/hidroqu/hidroqu-image/hidroqu-ml:latest

echo "Image pushed into artifact!"

